-- Faculty Academic Performance Dashboard (FAPD) - Database Schema

-- Create Database (Manual Step: CREATE DATABASE fapd_db;)
-- USE fapd_db;

-- 1. Users Table (Core Auth)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'faculty') NOT NULL DEFAULT 'faculty',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Faculty Profiles Table (Personal Info)
CREATE TABLE IF NOT EXISTS faculty_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    designation VARCHAR(100),
    phone VARCHAR(20),
    joined_year INT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Performance Table (KPI Data)
CREATE TABLE IF NOT EXISTS performance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty_id INT NOT NULL, -- Refers to faculty_profiles.id
    academic_year VARCHAR(20) NOT NULL,
    teaching_score DECIMAL(5,2) DEFAULT 0, -- Max 40
    research_score DECIMAL(5,2) DEFAULT 0, -- Max 30
    publications INT DEFAULT 0,
    publications_score DECIMAL(5,2) DEFAULT 0, -- Max 20
    other_score DECIMAL(5,2) DEFAULT 0, -- Max 10
    total_score DECIMAL(5,2) DEFAULT 0, -- Max 100
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (faculty_id) REFERENCES faculty_profiles(id) ON DELETE CASCADE,
    UNIQUE KEY unique_faculty_year (faculty_id, academic_year)
);

-- 4. Documents Table (Supporting Files)
CREATE TABLE IF NOT EXISTS documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty_id INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (faculty_id) REFERENCES faculty_profiles(id) ON DELETE CASCADE
);

-- Sample Data (Placeholders)
-- Note: Real bcrypt hashes will be generated by seed.js
-- admin password: Admin@123
INSERT INTO users (email, password, role) VALUES ('admin@fapd.edu', '$2b$10$PlaceholderHashForAdmin123', 'admin');
INSERT INTO users (email, password, role) VALUES ('faculty1@fapd.edu', '$2b$10$PlaceholderHashForAdmin123', 'faculty');
INSERT INTO users (email, password, role) VALUES ('faculty2@fapd.edu', '$2b$10$PlaceholderHashForAdmin123', 'faculty');

-- Sample Profiles
INSERT INTO faculty_profiles (user_id, name, department, designation, phone, joined_year) VALUES 
(1, 'System Admin', 'Administration', 'Administrator', '9999999999', 2024),
(2, 'Dr. Alice Smith', 'Computer Science', 'Professor', '9876543210', 2018),
(3, 'Dr. Bob Johnson', 'Information Technology', 'Associate Professor', '8765432109', 2020);

-- Sample Performance
INSERT INTO performance (faculty_id, academic_year, teaching_score, research_score, publications, publications_score, other_score, total_score, remarks) VALUES 
(2, '2023-24', 38.5, 25.0, 5, 18.0, 8.5, 90.0, 'Excellent performance in teaching and research.'),
(2, '2022-23', 35.0, 20.0, 3, 12.0, 7.0, 74.0, 'Good progress.'),
(3, '2023-24', 36.0, 22.0, 4, 15.0, 8.0, 81.0, 'Steadily improving.');
